// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xybhglryiewlfemduhrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5YmhnbHJ5aWV3bGZlbWR1aHJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MTEwNDksImV4cCI6MjA2MDM4NzA0OX0.Jbn8-MC5VrZfWczu3dqXHHuEV63USTwRCdhmDpqEGmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);